### ISSUE TITLE
Doesn't seem to work for the new Hue hub

### ISSUE THREAD

**Issue by derrickshowers** [jason0x43/alfred-hue#1]
I can't seem to get this workflow to work. I installed and typed 'hue hub'. When I select the option, nothing happens. I tried touching the connect button on the hub, but that doesn't seem to work either. Is it possible the new Hue hub isn't supported?

**Comment by jason0x43** [comment]
Try [v1.0.3](https://github.com/jason0x43/alfred-hue/releases/tag/v1.0.3)

**Comment by derrickshowers** [comment]
Works great. Thanks @jason0x43!
