### ISSUE TITLE
Scenes not working

### ISSUE THREAD

**Issue by derrickshowers** [jason0x43/alfred-hue#2]
Scenes seem to no longer work. Maybe it was caused by a Hue update? Correct scene data is in the cache'd JSON.

```
"Scenes": {
  "06b4e473d-on-0": {
    "name": "Trial 1 on 0",
    "owner": "none",
    "lastupdated": "",
    "lights": [
      "1",
      "2",
      "3",
      "4",
      "5",
      "6"
    ],
    "version": 1,
    "ID": "06b4e473d-on-0",
    "ShortName": "Trial 1"
  },
  "1105989c0-on-0": {
    "name": "Kathy on 0",
    "owner": "none",
    "lastupdated": "",
    "lights": [
      "1",
      "2",
      "3"
    ],
    "version": 1,
    "ID": "1105989c0-on-0",
    "ShortName": "Kathy"
  },
  ...
}
```

But, can not be found

![alfred_hue](https://cloud.githubusercontent.com/assets/1372292/14805816/50a798a8-0b24-11e6-8cc8-2e5b350284cb.gif)

Tried deleting the cached file and re-syncing, as well as reinstalling the workflow.

**Comment by jason0x43** [comment]
Are they working in [v2](https://github.com/jason0x43/alfred-hue/releases/tag/v2.0.0) (assuming you're still interested since this response is waaaaaaaaay late)? They're working for me, as much as they ever have (scenes from the hub have always been kind of messy).

**Comment by derrickshowers** [comment]
Thanks @jason0x43! I'll install v2 and check it out when I get home this evening.

**Comment by derrickshowers** [comment]
Doesn't seem to be working, but I noticed in your documentation you no longer mention scenes. Did you replace that with "presets" instead?

New version looks great!

**Comment by jason0x43** [comment]
Scenes should be working. What do you get when you try `hue scenes` (and press Enter)?

The documentation is, unfortunately, almost non-existent at the moment. I redid the workflow and wrote a basic README, but haven't gotten around to fleshing it out yet.

**Comment by derrickshowers** [comment]
Just selects the first option ("All lights"). Here's an example:

![alfred](https://cloud.githubusercontent.com/assets/1372292/26086339/e79a24f2-399e-11e7-97ea-623ae13d2ba8.gif)

**Comment by jason0x43** [comment]
That doesn't actually look like this workflow...

**Comment by derrickshowers** [comment]
Haha, no wonder. Embarrassing... 😳

Guess this happens when I upgraded per your suggestion the other day. Reinstalled the *correct* workflow and I now see scenes. Thanks! 😀

**Comment by jason0x43** [comment]
Great, glad to hear things are working :)
