### ISSUE TITLE
Exit status 1

### ISSUE THREAD

**Issue by ghost** [jason0x43/alfred-hue#3]
If I'm searching for a hub I'm able to see mine with the correct IP. If i push enter all i get is:

"Hue: Error: exit status 1"

 I'm on v1.0.3

**Comment by jason0x43** [comment]
Could you give [v2](https://github.com/jason0x43/alfred-hue/releases/tag/v2.0.0) a try?

**Comment by ghost** [comment]
![screen shot 2017-05-11 at 20 50 52](https://cloud.githubusercontent.com/assets/11852470/25966718/1edbdeda-368c-11e7-8678-722f2ad53706.png)

It apears after I've had to push the connect button of the hub.

**Comment by jason0x43** [comment]
Ah, I think I see what the issue is...

**Comment by jason0x43** [comment]
Try [2.0.1](https://github.com/jason0x43/alfred-hue/releases/tag/v2.0.1)

**Comment by ghost** [comment]
Works like a charm. Feel free to contact me anytime if you need someone to test.
